- name: task_description
  letsencrypt:
    csr: 
    #acme_directory: https://acme-staging.api.letsencrypt.org/directory
    #terms_agreed: 
    #account_email: 
    #dest: 
    #validate_certs: True
    #challenge: http-01
    #fullchain_dest: 
    #agreement: 
    #data: 
    #account_key_content: 
    #remaining_days: 10
    #acme_version: 1
    #chain_dest: 
    #account_key_src: 
